backend:
  name: git-gateway
  repo: freie-schule-bergmeilen/website
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/static/img"
public_folder: "img"

collections:

  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "Aktuelles" # Used in the UI
    folder: "src/pages/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {name: kind, widget: hidden, default: "news"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Pfad", name: "path", widget: "string"}
      - {label: "Titel", name: "title", widget: "string"}
      #- {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Pin", name: "pin", widget: "boolean"}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Template", name: "templateKey", widget: "hidden", default: "news-item" }

  - name: pages
    label: Seiten
    folder: "src/pages/added"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: kind, widget: hidden, default: "page"}
      - {label: "Pfad", name: "path", widget: "string"}
      - {label: "Titel", name: "title", widget: "string"}
      - label: Bereich
        name: section
        widget: select
        options: ["Angebot", "Philosophie", "Über uns"]
      - {label: "Text", name: "body", widget: "markdown"}


  - name: "fragments"
    label: "Fragmente"
    folder: "src/fragments"
    create: false
    slug: "{{slug}}"
    fields:
      - {name: dataKind, widget: hidden, default: "fragment"}
      - {label: "Titel", name: "title", widget: "string", required: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Path", name: "path", widget: "hidden"}


  - name: "settings"
    label: "Sonstiges"
    delete: false
    editor:
      preview: false
    files:
      - name: "metadata"
        label: "Globale Einstellungen"
        file: "data/site-metadata.yml"
        description: "Globale Einstellungen"
        fields:
          - {label: "Name der Webseite", name: title, widget: "string"}
          - {label: "Google Analytics UA-Code", name: trackingId, widget: "string"}
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - {label: "Überschrift", name: title, widget: string}
              - {label: "Text", name: text, widget: text}
          - label: "Aktuelles"
            name: news
            widget: object
            fields:
              - {label: "Anzahl News auf Homepage", name: numNewsItems, widget: number}

      - name: "goals"
        label: Ziele
        file: "data/goals.yml"
        description: "Ziele"
        fields:
          - {label: "Überschrift", name: title, widget: "string"}
          - name: goals
            label: Ziele
            widget: list
            fields:
              - {label: "Überschrift", name: title, widget: string}
              - {label: Beschreibung, name: description, widget: text, required: false}

      - name: "team"
        label: "Team"
        file: "data/team.yml"
        description: "Team"
        fields:
          - {label: "Überschrift", name: title, widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown", required: false}
          - name: teamMembers
            label: "Team Mitglieder"
            widget: list
            fields:
              - {name: name, label: Name}
              - {name: position, label: "Funktion and der Schule"}
              - {name: experience, label: "Ausbildung/Berufserfahrung", widget: text, required: false}
              - {name: photo, label: Foto, widget: image, required: false, class: "team-member" }
              - name: children
                label: Kinder
                widget: list
                required: false
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Year, name: year, widget: string}


#  - name: "about" # Used in routes, e.g., /admin/collections/blog
#    label: "Über uns" # Used in the UI
#    folder: "src/pages/about" # The path to the folder where the documents are stored
#    create: true # Allow users to create new documents in this collection
#    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#    fields: # The fields for each document, usually in front matter
#      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
#      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Body", name: "body", widget: "markdown"}
#      - {label: "Template", name: "templateKey", widget: "hidden", default: "page" }
